// Photo locations and equipment metadata
// Extracted from EXIF where available; locations added manually

export const photoMetadata = {
  1: { location: 'Caribbean Flag Dance', equipment: 'Sony A7R III + 70-200mm GM II' },
  2: { location: 'Tropical Island Paradise', equipment: 'Sony A7R III + 70-200mm GM II' },
  3: { location: 'Historic Lighthouse', equipment: 'Sony A7R III + 70-200mm GM II' },
  4: { location: 'Flag Bearer at Sunset', equipment: 'Sony A7R III + 70-200mm GM II' },
  5: { location: 'Coastal Rock Formation', equipment: 'Sony A7R III + 70-200mm GM II' },
  6: { location: 'Beach Sunset with Boat', equipment: 'Sony A7R III + 70-200mm GM II' },
  7: { location: 'Historic Tram', equipment: 'Sony A7R III + 16-35mm GM II' },
  8: { location: 'Rainforest Cathedral', equipment: 'Sony A7R III + 16-35mm GM II' },
  9: { location: 'Golden Gate Bridge Sunset', equipment: 'Sony A7R III + 70-200mm GM II' },
  10: { location: 'Tropical Anchorage', equipment: 'Sony A7R III + 70-200mm GM II' },
  11: { location: 'Green Iguana Portrait', equipment: 'Sony A7R III + 70-200mm GM II' },
  12: { location: 'Golden Gate Beach Waves', equipment: 'Sony A7R III + 16-35mm GM II' },
  13: { location: 'Abandoned Coastal House', equipment: 'Sony A7R III + 70-200mm GM II' },
  14: { location: 'Red Suspension Bridge', equipment: 'Sony A7R III + 16-35mm GM II' },
  15: { location: 'Arched Architecture', equipment: 'Sony A7R III + 16-35mm GM II' },
  16: { location: 'Coastal Palm Ruins', equipment: 'Sony A7R III + 16-35mm GM II' },
  17: { location: 'Colonial Alleyway', equipment: 'Sony A7R III + 16-35mm GM II' },
  18: { location: 'Burrowing Owl', equipment: 'Sony A7R III + 70-200mm GM II' },
  19: { location: 'Bald Eagle Portrait', equipment: 'Sony A7R III + 16-35mm GM II' },
  20: { location: 'Enchanted Forest', equipment: 'Sony A7R III + 70-200mm GM II' },
  21: { location: 'Temperate Rainforest', equipment: 'Sony A7R III + 70-200mm GM II' },
  22: { location: 'Forest Stream', equipment: 'Sony A7R III + 70-200mm GM II' },
  23: { location: 'Forest Cathedral', equipment: 'Sony A7R III + 16-35mm GM II' },
  24: { location: 'Rainbow Umbrella Installation', equipment: 'Sony A7R III + 16-35mm GM II' },
  25: { location: 'Anchor Line at Sunset', equipment: 'Sony A7R III + 16-35mm GM II' },
  26: { location: 'Night Sky Over Water', equipment: 'Nikon D7000 + 18-105mm' },
  27: { location: 'Blue Jay Detail', equipment: 'Sony A7R III + 20-70mm G' },
  28: { location: 'Forest Mood', equipment: 'Sony A7R III + 20-70mm G' },
  29: { location: 'Forest Bird', equipment: 'Sony A7R III + 20-70mm G' },
  30: { location: 'Tropical Bay Sunset', equipment: 'Sony A7R III + 20-70mm G' },
  31: { location: 'Vertical Forest', equipment: 'Sony A7R III + 70-200mm GM II' },
  32: { location: 'Calm Tropical Water', equipment: 'Sony A7R III + 16-35mm GM II' },
  33: { location: 'Snowy Forest', equipment: 'Sony A7R III + 70-200mm GM II' },
  34: { location: 'Winter Frost', equipment: 'Sony A7R III + 16-35mm GM II' },
  35: { location: 'Desert Canyon', equipment: 'Sony A7R III + 70-200mm GM II' },
  36: { location: 'Moody Terrain', equipment: 'Sony A7R III + 16-35mm GM II' },
  37: { location: 'Blue Sky Clouds', equipment: 'Sony A7R III + 16-35mm GM II' },
  38: { location: 'Geometric Interior', equipment: 'Sony A7R III + 16-35mm GM II' },
  39: { location: 'Weathered Wood Texture', equipment: 'Sony A7R III + 70-200mm GM II' },
  40: { location: 'Primordial Forest', equipment: 'Sony A7R III + 16-35mm GM II' },
  41: { location: 'Tropical Sunset', equipment: 'Sony A7R III + 16-35mm GM II' },
  42: { location: 'Dark Night Landscape', equipment: 'Sony A7R III + 70-200mm GM II' },
  43: { location: 'Desert Warmth', equipment: 'Sony A7R III + 70-200mm GM II' },
  44: { location: 'Desert Owl', equipment: 'Sony A7R III + 70-200mm GM II' },
  45: { location: 'Eagle Portrait', equipment: 'Sony A7R III + 70-200mm GM II' },
  46: { location: 'Majestic Eagle', equipment: 'Sony A7R III + 70-200mm GM II' },
};
