// Portfolio photographs by Łukasz Jagiełło.
// Real pixel dimensions and dominant colour extracted at build time using sharp.
// Titles and alt text written from direct visual review of each photograph (Oct 2026).
// `location` is shown on photo pages; leave it '' when unknown — never guess.
// `focus` (optional, CSS object-position) is the focal point used when a photo is cover-cropped (hero collage).
// `focusX` / `focusY` (optional, 0–1) are the same point as fractions of the source, for crops that need to center it.
// `categories` lists every lib/categories.js slug the photo belongs to (landscape | animals | architecture | people).
// A photo can sit in several, so per-category counts may add up past the total.
// `coords` (optional, { lat, lng, zoom }) places the photo on a map on its page. Approximate pins for known places;
// omit rather than guess. Photos with a `location` but no `coords` show the location text only.

export const photos = [
  { src: 'images/gallery/lightbox/lukasz-jagiello-01-full.webp', thumb: 'images/gallery/lukasz-jagiello-01-thumb.webp', alt: 'Dancer in camouflage holding a Jamaican flag aloft on stage, flags hanging from the ceiling behind him', categories: ['people'], title: 'Flag Bearer', location: 'Bloody Bay, Negril, Jamaica', coords: { lat: 18.335594, lng: -78.338469, zoom: 15 }, width: 1600, height: 2399, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-02-full.webp', thumb: 'images/gallery/lukasz-jagiello-02-thumb.webp', alt: 'Four dancers in green camouflage performing on a lit stage under Jamaican flags, audience watching', categories: ['people'], title: 'Jamaican Dance Troupe', location: 'Bloody Bay, Negril, Jamaica', coords: { lat: 18.335594, lng: -78.338469, zoom: 15 }, width: 1600, height: 1067, color: '#1d1501' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-03-full.webp', thumb: 'images/gallery/lukasz-jagiello-03-thumb.webp', alt: 'Negril Lighthouse in Jamaica rising above trees and limestone cliffs under a deep blue sky', categories: ['architecture', 'landscape'], title: 'Negril Lighthouse', location: 'Negril, Jamaica', coords: { lat: 18.2447, lng: -78.3657, zoom: 15 }, width: 1600, height: 1067, color: '#0079ad' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-04-full.webp', thumb: 'images/gallery/lukasz-jagiello-04-thumb.webp', alt: 'White Negril Lighthouse with a red lantern room and railing, rising above a rocky cliff and green trees under a purple and pink cloudy sky', categories: ['architecture', 'landscape'], title: 'Negril Lighthouse in Daylight', location: 'Negril, Jamaica', coords: { lat: 18.2447, lng: -78.3657, zoom: 15 }, width: 1600, height: 2399, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-05-full.webp', thumb: 'images/gallery/lukasz-jagiello-05-thumb.webp', alt: 'Small white boat on dark rippling water beneath heavy storm clouds along a tropical shoreline', categories: ['landscape', 'people'], title: 'Lone Boat Under Storm Clouds', location: 'Seven Mile Beach, Negril, Jamaica', coords: { lat: 18.323359, lng: -78.361371, zoom: 14 }, width: 1600, height: 2399, color: '#515e61' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-06-full.webp', thumb: 'images/gallery/lukasz-jagiello-06-thumb.webp', alt: 'Black-and-white view of a storm-damaged beachfront building with a lone figure walking the sand', categories: ['architecture', 'landscape'], title: 'After the Storm', location: 'Seven Mile Beach, Negril, Jamaica', coords: { lat: 18.284092, lng: -78.343844, zoom: 14 }, width: 1600, height: 1067, color: '#e1d8c7' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-07-full.webp', thumb: 'images/gallery/lukasz-jagiello-07-thumb.webp', alt: 'Boats moored on calm water beneath a dramatic orange and grey sunset sky', categories: ['landscape'], title: 'Anchorage at Sunset', location: 'Bloody Bay, Negril, Jamaica', focus: '50% 40%', coords: { lat: 18.334421, lng: -78.339445, zoom: 15 }, width: 1600, height: 1067, color: '#031720' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-08-full.webp', thumb: 'images/gallery/lukasz-jagiello-08-thumb.webp', alt: 'Alcatraz Island water tower and concrete guard structure framed by palm fronds and greenery', categories: ['architecture'], title: 'Alcatraz Water Tower', location: 'Alcatraz Island, San Francisco', coords: { lat: 37.8267, lng: -122.423, zoom: 15 }, width: 1600, height: 2399, color: '#b8d1f0' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-09-full.webp', thumb: 'images/gallery/lukasz-jagiello-09-thumb.webp', alt: 'Yellow and white vintage streetcar number 1057 on tree-lined tracks in San Francisco', categories: ['architecture'], title: 'Streetcar 1057', location: 'The Embarcadero at Pier 39, San Francisco', coords: { lat: 37.806982, lng: -122.410074, zoom: 16 }, width: 1600, height: 2399, color: '#02170b' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-10-full.webp', thumb: 'images/gallery/lukasz-jagiello-10-thumb.webp', alt: 'San Francisco cable car number 12 descending a steep street lined with parked cars', categories: ['architecture'], title: 'Cable Car on the Hill', location: 'Hyde Street, San Francisco', coords: { lat: 37.805286, lng: -122.41526, zoom: 16 }, width: 1600, height: 2399, color: '#031b0e' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-11-full.webp', thumb: 'images/gallery/lukasz-jagiello-11-thumb.webp', alt: 'Golden Gate Bridge spanning the bay with turquoise water and waves breaking on rocks', categories: ['landscape', 'architecture'], title: 'Golden Gate Surf', location: 'Golden Gate Bridge, San Francisco', coords: { lat: 37.7936, lng: -122.4836, zoom: 14 }, width: 1600, height: 900, color: '#9fc7c6' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-12-full.webp', thumb: 'images/gallery/lukasz-jagiello-12-thumb.webp', alt: 'Silky waves washing over rocks with the Golden Gate Bridge in the distance', categories: ['landscape', 'architecture'], title: 'Golden Gate Long Exposure', location: 'Golden Gate Bridge, San Francisco', focus: '50% 12%', coords: { lat: 37.7936, lng: -122.4836, zoom: 14 }, width: 1600, height: 2400, color: '#00a6cd' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-13-full.webp', thumb: 'images/gallery/lukasz-jagiello-13-thumb.webp', alt: 'Rear view of a Powell and Market cable car with a gripman in a safety vest on a busy street', categories: ['architecture', 'people'], title: 'Powell–Market Cable Car', location: 'Fisherman\'s Wharf, San Francisco', coords: { lat: 37.804078, lng: -122.42006, zoom: 16 }, width: 1600, height: 2399, color: '#202020' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-14-full.webp', thumb: 'images/gallery/lukasz-jagiello-14-thumb.webp', alt: 'Row of Victorian houses at Alamo Square with the San Francisco skyline behind them', categories: ['architecture'], title: 'Painted Ladies', location: 'Alamo Square, San Francisco', coords: { lat: 37.7763, lng: -122.4328, zoom: 16 }, width: 1600, height: 900, color: '#012273' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-15-full.webp', thumb: 'images/gallery/lukasz-jagiello-15-thumb.webp', alt: 'Golden Gate Bridge tower and red cables seen from the Fort Point side under clear skies', categories: ['architecture', 'landscape'], title: 'Golden Gate from Fort Point', location: 'Golden Gate Bridge, San Francisco', coords: { lat: 37.8107, lng: -122.477, zoom: 15 }, width: 1600, height: 1067, color: '#004586' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-16-full.webp', thumb: 'images/gallery/lukasz-jagiello-16-thumb.webp', alt: 'Looking straight up a Golden Gate Bridge tower and suspension cables against blue sky', categories: ['architecture'], title: 'Looking Up the Tower', location: 'Golden Gate Bridge, San Francisco', coords: { lat: 37.8199, lng: -122.4783, zoom: 15 }, width: 1600, height: 2400, color: '#0056a9' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-17-full.webp', thumb: 'images/gallery/lukasz-jagiello-17-thumb.webp', alt: 'Two-lane road with a yellow centre line running between towering redwood trees', categories: ['landscape'], title: 'Redwood Highway', location: '', width: 1600, height: 2070, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-18-full.webp', thumb: 'images/gallery/lukasz-jagiello-18-thumb.webp', alt: 'Cow elk standing in golden grass against a dark green forest edge', categories: ['animals', 'landscape'], title: 'Elk in Tall Grass', location: 'Near Crescent City, California', coords: { lat: 41.735386, lng: -124.152543, zoom: 13 }, width: 1600, height: 1000, color: '#01001f' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-19-full.webp', thumb: 'images/gallery/lukasz-jagiello-19-thumb.webp', alt: 'Emerald-green Smith River winding through a rocky forested canyon along Highway 199 in Northern California, pink evening sky above', categories: ['landscape'], title: 'Smith River Canyon', location: 'Smith River, Highway 199 near Gasquet, California', coords: { lat: 41.839553, lng: -124.03418, zoom: 12 }, width: 1600, height: 2399, color: '#737d96' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-20-full.webp', thumb: 'images/gallery/lukasz-jagiello-20-thumb.webp', alt: 'Green iguana climbing among bright green stems, lit from behind', categories: ['animals'], title: 'Green Iguana in the Reeds', location: 'Puerto Los Cabos, San José del Cabo, Mexico', coords: { lat: 23.065926, lng: -109.659441, zoom: 14 }, width: 1600, height: 2399, color: '#001c00' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-21-full.webp', thumb: 'images/gallery/lukasz-jagiello-21-thumb.webp', alt: 'Green iguana resting among palm fronds with sunlight filtering through', categories: ['animals'], title: 'Iguana in the Palms', location: 'Puerto Los Cabos, San José del Cabo, Mexico', coords: { lat: 23.065926, lng: -109.659441, zoom: 14 }, width: 1600, height: 2399, color: '#004400' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-22-full.webp', thumb: 'images/gallery/lukasz-jagiello-22-thumb.webp', alt: 'Green iguana on gravel beside a weathered log, head down among sprouting seedlings', categories: ['animals'], title: 'Iguana Foraging', location: 'Puerto Los Cabos, San José del Cabo, Mexico', coords: { lat: 23.065926, lng: -109.659441, zoom: 14 }, width: 1600, height: 1143, color: '#000a00' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-23-full.webp', thumb: 'images/gallery/lukasz-jagiello-23-thumb.webp', alt: 'Narrow sandstone slot canyon glowing orange with a sliver of blue sky above', categories: ['landscape'], title: 'Slot Canyon Light', location: 'Lower Antelope Canyon, Page, Arizona', coords: { lat: 36.903136, lng: -111.413248, zoom: 15 }, width: 1600, height: 2399, color: '#011401' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-24-full.webp', thumb: 'images/gallery/lukasz-jagiello-24-thumb.webp', alt: 'Abandoned motorboat washed up on a sandy beach beneath palm trees and a stormy pink sky', categories: ['landscape'], title: 'Beached Boat', location: 'Bloody Bay, Negril, Jamaica', coords: { lat: 18.332807, lng: -78.337865, zoom: 15 }, width: 1600, height: 1067, color: '#cca478' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-25-full.webp', thumb: 'images/gallery/lukasz-jagiello-25-thumb.webp', alt: 'Buoy line stretching across calm water toward anchored boats under a golden sunset', categories: ['landscape'], title: 'Swim Line at Sunset', location: 'Bloody Bay, Negril, Jamaica', coords: { lat: 18.331724, lng: -78.337593, zoom: 15 }, width: 1600, height: 1067, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-26-full.webp', thumb: 'images/gallery/lukasz-jagiello-26-thumb.webp', alt: 'Black-and-white image of a brown bear walking over fallen logs below a rock wall', categories: ['animals'], title: 'Bear Among the Logs', location: 'Bearizona Wildlife Park, Williams, Arizona', coords: { lat: 35.254882, lng: -112.15319, zoom: 15 }, width: 1600, height: 1060, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-27-full.webp', thumb: 'images/gallery/lukasz-jagiello-27-thumb.webp', alt: 'Looking up through golden autumn aspen trunks to a clear blue sky', categories: ['landscape'], title: 'Aspen Canopy', location: 'San Francisco Peaks, Flagstaff, Arizona', coords: { lat: 35.333927, lng: -111.701523, zoom: 12 }, width: 1600, height: 1067, color: '#91c5fb' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-28-full.webp', thumb: 'images/gallery/lukasz-jagiello-28-thumb.webp', alt: 'Overgrown trees framing a collapsing wooden shack and old vehicle in dappled light', categories: ['landscape', 'architecture'], title: 'Forgotten Homestead', location: 'San Tan Valley, Arizona', coords: { lat: 33.278436, lng: -111.157071, zoom: 13 }, width: 1600, height: 2399, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-29-full.webp', thumb: 'images/gallery/lukasz-jagiello-29-thumb.webp', alt: 'Squirrel monkey staring into the camera from a wooden rail, blurred foliage behind', categories: ['animals'], title: 'Squirrel Monkey', location: 'Punta Cana, Dominican Republic', coords: { lat: 18.696402, lng: -68.66928, zoom: 13 }, width: 1600, height: 1067, color: '#060c07' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-30-full.webp', thumb: 'images/gallery/lukasz-jagiello-30-thumb.webp', alt: 'Rows of rainbow-striped umbrellas suspended overhead against a cloudy sky', categories: ['architecture'], title: 'Rainbow Umbrellas', location: 'Punta Cana, Dominican Republic', coords: { lat: 18.696402, lng: -68.66928, zoom: 13 }, width: 1600, height: 1230, color: '#f2e9e2' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-31-full.webp', thumb: 'images/gallery/lukasz-jagiello-31-thumb.webp', alt: 'Black oystercatcher with bright orange bill standing on gravel near the shore', categories: ['animals'], title: 'Black Oystercatcher', location: 'Monterey Bay Aquarium, Monterey, California', coords: { lat: 36.618477, lng: -121.901901, zoom: 16 }, width: 1600, height: 2845, color: '#39474f' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-32-full.webp', thumb: 'images/gallery/lukasz-jagiello-32-thumb.webp', alt: 'Seattle skyline with the Space Needle seen across the water under scattered clouds', categories: ['architecture', 'landscape'], title: 'Seattle Skyline', location: 'Seattle, Washington', coords: { lat: 47.6062, lng: -122.3421, zoom: 13 }, width: 1600, height: 900, color: '#007cb2' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-33-full.webp', thumb: 'images/gallery/lukasz-jagiello-33-thumb.webp', alt: 'White-sailed sailboat heeling on blue water with mountains and cumulus clouds behind', categories: ['landscape', 'people'], title: 'Under Full Sail', location: 'Anacortes, Washington', coords: { lat: 48.428967, lng: -122.710308, zoom: 13 }, width: 1600, height: 2845, color: '#fcfcfc' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-34-full.webp', thumb: 'images/gallery/lukasz-jagiello-34-thumb.webp', alt: 'Waterfall tumbling below a footbridge with Mount Rainier\'s glaciers in the background', categories: ['landscape'], title: 'Myrtle Falls', location: 'Mount Rainier National Park, Washington', coords: { lat: 46.792, lng: -121.729, zoom: 15 }, width: 1600, height: 2272, color: '#fafafa' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-35-full.webp', thumb: 'images/gallery/lukasz-jagiello-35-thumb.webp', alt: 'Steller\'s jay with blue plumage perched among fir branches', categories: ['animals'], title: 'Steller\'s Jay', location: 'Paradise, Mount Rainier National Park, Washington', coords: { lat: 46.773335, lng: -121.744275, zoom: 14 }, width: 1600, height: 2036, color: '#56371c' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-36-full.webp', thumb: 'images/gallery/lukasz-jagiello-36-thumb.webp', alt: 'Waterfall framed by a stone arch bridge in a mossy forest gorge', categories: ['landscape', 'architecture'], title: 'Christine Falls', location: 'Mount Rainier National Park, Washington', coords: { lat: 46.7813, lng: -121.7801, zoom: 15 }, width: 1600, height: 2399, color: '#1a1610' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-37-full.webp', thumb: 'images/gallery/lukasz-jagiello-37-thumb.webp', alt: 'Snoqualmie Falls plunging into a misty pool with lush greenery in the foreground', categories: ['landscape'], title: 'Snoqualmie Falls', location: 'Snoqualmie Falls, Washington', coords: { lat: 47.5417, lng: -121.8377, zoom: 15 }, width: 1600, height: 2473, color: '#f3f4f8' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-38-full.webp', thumb: 'images/gallery/lukasz-jagiello-38-thumb.webp', alt: 'Snoqualmie Falls and the lodge above it seen from the canyon rim with autumn colour', categories: ['landscape'], title: 'Snoqualmie Falls from Above', location: 'Snoqualmie Falls, Washington', focus: '50% 50%', coords: { lat: 47.5417, lng: -121.8377, zoom: 15 }, width: 1600, height: 1067, color: '#100e0e' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-39-full.webp', thumb: 'images/gallery/lukasz-jagiello-39-thumb.webp', alt: 'Forested sea stacks and driftwood-strewn sand at Ruby Beach on the Washington coast under a pink streaked sky', categories: ['landscape'], title: 'Ruby Beach', location: 'Ruby Beach, Washington', focus: '50% 45%', coords: { lat: 47.7106, lng: -124.4156, zoom: 13 }, width: 1600, height: 1000, color: '#221a18' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-40-full.webp', thumb: 'images/gallery/lukasz-jagiello-40-thumb.webp', alt: 'Moss-draped trees and ferns in a dense Pacific Northwest rainforest', categories: ['landscape'], title: 'Mossy Rainforest', location: 'Marymere Falls Trail, Olympic National Park, Washington', coords: { lat: 48.052251, lng: -123.788082, zoom: 14 }, width: 1600, height: 2071, color: '#080401' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-41-full.webp', thumb: 'images/gallery/lukasz-jagiello-41-thumb.webp', alt: 'Marymere Falls cascading over a moss-covered cliff in the old-growth forest of Olympic National Park, Washington', categories: ['landscape'], title: 'Marymere Falls', location: 'Marymere Falls, Olympic National Park, Washington', focus: '68% 50%', focusX: 0.65, focusY: 0.45, coords: { lat: 48.0533, lng: -123.7895, zoom: 14 }, width: 1600, height: 1000, color: '#020709' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-42-full.webp', thumb: 'images/gallery/lukasz-jagiello-42-thumb.webp', alt: 'Bighorn sheep ram resting in a shaft of light between dark tree trunks', categories: ['animals'], title: 'Bighorn in the Shadows', location: 'Bearizona Wildlife Park, Williams, Arizona', coords: { lat: 35.254882, lng: -112.15319, zoom: 15 }, width: 1600, height: 1067, color: '#010101' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-43-full.webp', thumb: 'images/gallery/lukasz-jagiello-43-thumb.webp', alt: 'Glossy black crested bird perched on a pine branch against blue sky', categories: ['animals'], title: 'Phainopepla', location: 'Bearizona Wildlife Park, Williams, Arizona', coords: { lat: 35.254882, lng: -112.15319, zoom: 15 }, width: 1600, height: 1067, color: '#3d342e' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-44-full.webp', thumb: 'images/gallery/lukasz-jagiello-44-thumb.webp', alt: 'Burrowing owl standing on a log, staring at the camera with yellow eyes', categories: ['animals'], title: 'Burrowing Owl on a Log', location: 'Wildlife World Zoo, Litchfield Park, Arizona', coords: { lat: 33.550283, lng: -112.411488, zoom: 15 }, width: 1600, height: 2400, color: '#010101' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-45-full.webp', thumb: 'images/gallery/lukasz-jagiello-45-thumb.webp', alt: 'Burrowing owl framed in the dark entrance of a rocky burrow', categories: ['animals'], title: 'Owl at the Burrow', location: 'Wildlife World Zoo, Litchfield Park, Arizona', coords: { lat: 33.550283, lng: -112.411488, zoom: 15 }, width: 1600, height: 2400, color: '#010101' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-46-full.webp', thumb: 'images/gallery/lukasz-jagiello-46-thumb.webp', alt: 'Bald eagle in profile with white head and yellow beak, dark feathers glistening', categories: ['animals'], title: 'Bald Eagle', location: 'Wildlife World Zoo, Litchfield Park, Arizona', coords: { lat: 33.550283, lng: -112.411488, zoom: 15 }, width: 1600, height: 2400, color: '#000000' },
];

export const hero = {
  // Bottom crop of photo 41 (DSC05293). Variants: scripts/generate-hero.mjs.
  src: 'images/hero/lukasz-jagiello-hero-1920.webp',
  alt: 'Pacific coastline at golden hour with layered headlands fading into haze',
  widths: [1280, 1920, 2560],
};
