// Portfolio photographs by Łukasz Jagiełło.
// Real pixel dimensions and dominant colour extracted at build time using sharp.
// Titles and alt text written from direct visual review of each photograph (Oct 2026).
// `location` is shown on photo pages; leave it '' when unknown — never guess.
// `focus` (optional, CSS object-position) is the focal point used when a photo is cover-cropped (hero collage).
// `coords` (optional, { lat, lng, zoom }) places the photo on a map on its page. Approximate pins for known places;
// omit rather than guess. Photos with a `location` but no `coords` show the location text only.

export const photos = [
  { src: 'images/gallery/lightbox/lukasz-jagiello-01-full.webp', thumb: 'images/gallery/lukasz-jagiello-01-thumb.webp', alt: 'Dancer in camouflage holding a Jamaican flag aloft on stage, flags hanging from the ceiling behind him', title: 'Flag Bearer', location: 'Jamaica', width: 1600, height: 2399, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-02-full.webp', thumb: 'images/gallery/lukasz-jagiello-02-thumb.webp', alt: 'Four dancers in green camouflage performing on a lit stage under Jamaican flags, audience watching', title: 'Jamaican Dance Troupe', location: 'Jamaica', width: 1600, height: 1067, color: '#1d1501' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-03-full.webp', thumb: 'images/gallery/lukasz-jagiello-03-thumb.webp', alt: 'Negril Lighthouse in Jamaica rising above trees and limestone cliffs under a deep blue sky', title: 'Negril Lighthouse', location: 'Negril, Jamaica', coords: { lat: 18.2447, lng: -78.3657, zoom: 15 }, width: 1600, height: 1067, color: '#0079ad' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-04-full.webp', thumb: 'images/gallery/lukasz-jagiello-04-thumb.webp', alt: 'Negril Lighthouse in Jamaica glowing against a purple and pink dusk sky, tropical trees in the foreground', title: 'Negril Lighthouse at Dusk', location: 'Negril, Jamaica', coords: { lat: 18.2447, lng: -78.3657, zoom: 15 }, width: 1600, height: 2399, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-05-full.webp', thumb: 'images/gallery/lukasz-jagiello-05-thumb.webp', alt: 'Small white boat on dark rippling water beneath heavy storm clouds along a tropical shoreline', title: 'Lone Boat Under Storm Clouds', location: '', width: 1600, height: 2399, color: '#515e61' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-06-full.webp', thumb: 'images/gallery/lukasz-jagiello-06-thumb.webp', alt: 'Black-and-white view of a storm-damaged beachfront building with a lone figure walking the sand', title: 'After the Storm', location: '', width: 1600, height: 1067, color: '#e1d8c7' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-07-full.webp', thumb: 'images/gallery/lukasz-jagiello-07-thumb.webp', alt: 'Boats moored on calm water beneath a dramatic orange and grey sunset sky', title: 'Anchorage at Sunset', location: '', focus: '50% 40%', width: 1600, height: 1067, color: '#031720' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-08-full.webp', thumb: 'images/gallery/lukasz-jagiello-08-thumb.webp', alt: 'Alcatraz Island water tower and concrete guard structure framed by palm fronds and greenery', title: 'Alcatraz Water Tower', location: 'Alcatraz Island, San Francisco', coords: { lat: 37.8267, lng: -122.423, zoom: 15 }, width: 1600, height: 2399, color: '#b8d1f0' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-09-full.webp', thumb: 'images/gallery/lukasz-jagiello-09-thumb.webp', alt: 'Yellow and white vintage streetcar number 1057 on tree-lined tracks in San Francisco', title: 'Streetcar 1057', location: 'San Francisco', width: 1600, height: 2399, color: '#02170b' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-10-full.webp', thumb: 'images/gallery/lukasz-jagiello-10-thumb.webp', alt: 'San Francisco cable car number 12 descending a steep street lined with parked cars', title: 'Cable Car on the Hill', location: 'San Francisco', width: 1600, height: 2399, color: '#031b0e' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-11-full.webp', thumb: 'images/gallery/lukasz-jagiello-11-thumb.webp', alt: 'Golden Gate Bridge spanning the bay with turquoise water and waves breaking on rocks', title: 'Golden Gate Surf', location: 'Golden Gate Bridge, San Francisco', coords: { lat: 37.7936, lng: -122.4836, zoom: 14 }, width: 1600, height: 900, color: '#9fc7c6' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-12-full.webp', thumb: 'images/gallery/lukasz-jagiello-12-thumb.webp', alt: 'Silky waves washing over rocks with the Golden Gate Bridge in the distance', title: 'Golden Gate Long Exposure', location: 'Golden Gate Bridge, San Francisco', focus: '50% 12%', coords: { lat: 37.7936, lng: -122.4836, zoom: 14 }, width: 1600, height: 2400, color: '#00a6cd' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-13-full.webp', thumb: 'images/gallery/lukasz-jagiello-13-thumb.webp', alt: 'Rear view of a Powell and Market cable car with a gripman in a safety vest on a busy street', title: 'Powell–Market Cable Car', location: 'San Francisco', width: 1600, height: 2399, color: '#202020' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-14-full.webp', thumb: 'images/gallery/lukasz-jagiello-14-thumb.webp', alt: 'Row of Victorian houses at Alamo Square with the San Francisco skyline behind them', title: 'Painted Ladies', location: 'Alamo Square, San Francisco', coords: { lat: 37.7763, lng: -122.4328, zoom: 16 }, width: 1600, height: 900, color: '#012273' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-15-full.webp', thumb: 'images/gallery/lukasz-jagiello-15-thumb.webp', alt: 'Golden Gate Bridge tower and red cables seen from the Fort Point side under clear skies', title: 'Golden Gate from Fort Point', location: 'Golden Gate Bridge, San Francisco', coords: { lat: 37.8107, lng: -122.477, zoom: 15 }, width: 1600, height: 1067, color: '#004586' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-16-full.webp', thumb: 'images/gallery/lukasz-jagiello-16-thumb.webp', alt: 'Looking straight up a Golden Gate Bridge tower and suspension cables against blue sky', title: 'Looking Up the Tower', location: 'Golden Gate Bridge, San Francisco', coords: { lat: 37.8199, lng: -122.4783, zoom: 15 }, width: 1600, height: 2400, color: '#0056a9' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-17-full.webp', thumb: 'images/gallery/lukasz-jagiello-17-thumb.webp', alt: 'Two-lane road with a yellow centre line running between towering redwood trees', title: 'Redwood Highway', location: '', width: 1600, height: 2070, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-18-full.webp', thumb: 'images/gallery/lukasz-jagiello-18-thumb.webp', alt: 'Cow elk standing in golden grass against a dark green forest edge', title: 'Elk in Tall Grass', location: '', width: 1600, height: 1000, color: '#01001f' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-19-full.webp', thumb: 'images/gallery/lukasz-jagiello-19-thumb.webp', alt: 'Emerald-green Smith River winding through a rocky forested canyon along Highway 199 in Northern California, pink evening sky above', title: 'Smith River Canyon', location: 'Smith River, Highway 199, Northern California', coords: { lat: 41.7996, lng: -124.0557, zoom: 11 }, width: 1600, height: 2399, color: '#737d96' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-20-full.webp', thumb: 'images/gallery/lukasz-jagiello-20-thumb.webp', alt: 'Green iguana climbing among bright green stems, lit from behind', title: 'Green Iguana in the Reeds', location: '', width: 1600, height: 2399, color: '#001c00' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-21-full.webp', thumb: 'images/gallery/lukasz-jagiello-21-thumb.webp', alt: 'Green iguana resting among palm fronds with sunlight filtering through', title: 'Iguana in the Palms', location: '', width: 1600, height: 2399, color: '#004400' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-22-full.webp', thumb: 'images/gallery/lukasz-jagiello-22-thumb.webp', alt: 'Green iguana on gravel beside a weathered log, head down among sprouting seedlings', title: 'Iguana Foraging', location: '', width: 1600, height: 1143, color: '#000a00' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-23-full.webp', thumb: 'images/gallery/lukasz-jagiello-23-thumb.webp', alt: 'Narrow sandstone slot canyon glowing orange with a sliver of blue sky above', title: 'Slot Canyon Light', location: '', width: 1600, height: 2399, color: '#011401' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-24-full.webp', thumb: 'images/gallery/lukasz-jagiello-24-thumb.webp', alt: 'Abandoned motorboat washed up on a sandy beach beneath palm trees and a stormy pink sky', title: 'Beached Boat', location: '', width: 1600, height: 1067, color: '#cca478' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-25-full.webp', thumb: 'images/gallery/lukasz-jagiello-25-thumb.webp', alt: 'Buoy line stretching across calm water toward anchored boats under a golden sunset', title: 'Swim Line at Sunset', location: '', width: 1600, height: 1067, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-26-full.webp', thumb: 'images/gallery/lukasz-jagiello-26-thumb.webp', alt: 'Black-and-white image of a brown bear walking over fallen logs below a rock wall', title: 'Bear Among the Logs', location: '', width: 1600, height: 1060, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-27-full.webp', thumb: 'images/gallery/lukasz-jagiello-27-thumb.webp', alt: 'Looking up through golden autumn aspen trunks to a clear blue sky', title: 'Aspen Canopy', location: '', width: 1600, height: 1067, color: '#91c5fb' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-28-full.webp', thumb: 'images/gallery/lukasz-jagiello-28-thumb.webp', alt: 'Overgrown trees framing a collapsing wooden shack and old vehicle in dappled light', title: 'Forgotten Homestead', location: '', width: 1600, height: 2399, color: '#000000' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-29-full.webp', thumb: 'images/gallery/lukasz-jagiello-29-thumb.webp', alt: 'Squirrel monkey staring into the camera from a wooden rail, blurred foliage behind', title: 'Squirrel Monkey', location: '', width: 1600, height: 1067, color: '#060c07' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-30-full.webp', thumb: 'images/gallery/lukasz-jagiello-30-thumb.webp', alt: 'Rows of rainbow-striped umbrellas suspended overhead against a cloudy sky', title: 'Rainbow Umbrellas', location: '', width: 1600, height: 1230, color: '#f2e9e2' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-31-full.webp', thumb: 'images/gallery/lukasz-jagiello-31-thumb.webp', alt: 'Black oystercatcher with bright orange bill standing on gravel near the shore', title: 'Black Oystercatcher', location: '', width: 1600, height: 2845, color: '#39474f' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-32-full.webp', thumb: 'images/gallery/lukasz-jagiello-32-thumb.webp', alt: 'Seattle skyline with the Space Needle seen across the water under scattered clouds', title: 'Seattle Skyline', location: 'Seattle, Washington', coords: { lat: 47.6062, lng: -122.3421, zoom: 13 }, width: 1600, height: 900, color: '#007cb2' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-33-full.webp', thumb: 'images/gallery/lukasz-jagiello-33-thumb.webp', alt: 'White-sailed sailboat heeling on blue water with mountains and cumulus clouds behind', title: 'Under Full Sail', location: '', width: 1600, height: 2845, color: '#fcfcfc' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-34-full.webp', thumb: 'images/gallery/lukasz-jagiello-34-thumb.webp', alt: 'Waterfall tumbling below a footbridge with Mount Rainier\'s glaciers in the background', title: 'Myrtle Falls', location: 'Mount Rainier National Park, Washington', coords: { lat: 46.792, lng: -121.729, zoom: 15 }, width: 1600, height: 2272, color: '#fafafa' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-35-full.webp', thumb: 'images/gallery/lukasz-jagiello-35-thumb.webp', alt: 'Steller\'s jay with blue plumage perched among fir branches', title: 'Steller\'s Jay', location: '', width: 1600, height: 2036, color: '#56371c' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-36-full.webp', thumb: 'images/gallery/lukasz-jagiello-36-thumb.webp', alt: 'Waterfall framed by a stone arch bridge in a mossy forest gorge', title: 'Christine Falls', location: 'Mount Rainier National Park, Washington', coords: { lat: 46.7813, lng: -121.7801, zoom: 15 }, width: 1600, height: 2399, color: '#1a1610' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-37-full.webp', thumb: 'images/gallery/lukasz-jagiello-37-thumb.webp', alt: 'Snoqualmie Falls plunging into a misty pool with lush greenery in the foreground', title: 'Snoqualmie Falls', location: 'Snoqualmie Falls, Washington', coords: { lat: 47.5417, lng: -121.8377, zoom: 15 }, width: 1600, height: 2473, color: '#f3f4f8' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-38-full.webp', thumb: 'images/gallery/lukasz-jagiello-38-thumb.webp', alt: 'Snoqualmie Falls and the lodge above it seen from the canyon rim with autumn colour', title: 'Snoqualmie Falls from Above', location: 'Snoqualmie Falls, Washington', focus: '50% 50%', coords: { lat: 47.5417, lng: -121.8377, zoom: 15 }, width: 1600, height: 1067, color: '#100e0e' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-39-full.webp', thumb: 'images/gallery/lukasz-jagiello-39-thumb.webp', alt: 'Forested sea stacks and driftwood-strewn sand at Ruby Beach on the Washington coast under a pink streaked sky', title: 'Ruby Beach', location: 'Ruby Beach, Washington', focus: '50% 45%', coords: { lat: 47.7106, lng: -124.4156, zoom: 13 }, width: 1600, height: 1000, color: '#221a18' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-40-full.webp', thumb: 'images/gallery/lukasz-jagiello-40-thumb.webp', alt: 'Moss-draped trees and ferns in a dense Pacific Northwest rainforest', title: 'Mossy Rainforest', location: '', width: 1600, height: 2071, color: '#080401' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-41-full.webp', thumb: 'images/gallery/lukasz-jagiello-41-thumb.webp', alt: 'Marymere Falls cascading over a moss-covered cliff in the old-growth forest of Olympic National Park, Washington', title: 'Marymere Falls', location: 'Marymere Falls, Olympic National Park, Washington', focus: '68% 50%', coords: { lat: 48.0533, lng: -123.7895, zoom: 14 }, width: 1600, height: 1000, color: '#020709' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-42-full.webp', thumb: 'images/gallery/lukasz-jagiello-42-thumb.webp', alt: 'Bighorn sheep ram resting in a shaft of light between dark tree trunks', title: 'Bighorn in the Shadows', location: '', width: 1600, height: 1067, color: '#010101' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-43-full.webp', thumb: 'images/gallery/lukasz-jagiello-43-thumb.webp', alt: 'Glossy black crested bird perched on a pine branch against blue sky', title: 'Phainopepla', location: '', width: 1600, height: 1067, color: '#3d342e' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-44-full.webp', thumb: 'images/gallery/lukasz-jagiello-44-thumb.webp', alt: 'Burrowing owl standing on a log, staring at the camera with yellow eyes', title: 'Burrowing Owl on a Log', location: '', width: 1600, height: 2400, color: '#010101' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-45-full.webp', thumb: 'images/gallery/lukasz-jagiello-45-thumb.webp', alt: 'Burrowing owl framed in the dark entrance of a rocky burrow', title: 'Owl at the Burrow', location: '', width: 1600, height: 2400, color: '#010101' },
  { src: 'images/gallery/lightbox/lukasz-jagiello-46-full.webp', thumb: 'images/gallery/lukasz-jagiello-46-thumb.webp', alt: 'Bald eagle in profile with white head and yellow beak, dark feathers glistening', title: 'Bald Eagle', location: '', width: 1600, height: 2400, color: '#000000' },
];

export const hero = {
  src: 'images/lukasz-jagiello-hero.webp',
  alt: 'Pacific coastline at golden hour with layered headlands fading into haze',
};
