// Portfolio photographs by Łukasz Jagiełło.
// Real pixel dimensions and dominant colour extracted at build time using sharp.
// Location data is read from image metadata only.

export const photos = [
  { src: 'gallery/lightbox/lukasz-jagiello-01-full.webp', thumb: 'gallery/lukasz-jagiello-01-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 1', title: 'Photograph 1', width: 1600, height: 2399, color: '#000000' },
  { src: 'gallery/lightbox/lukasz-jagiello-02-full.webp', thumb: 'gallery/lukasz-jagiello-02-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 2', title: 'Photograph 2', width: 1600, height: 1067, color: '#1d1501' },
  { src: 'gallery/lightbox/lukasz-jagiello-03-full.webp', thumb: 'gallery/lukasz-jagiello-03-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 3', title: 'Photograph 3', width: 1600, height: 1067, color: '#0079ad' },
  { src: 'gallery/lightbox/lukasz-jagiello-04-full.webp', thumb: 'gallery/lukasz-jagiello-04-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 4', title: 'Photograph 4', width: 1600, height: 2399, color: '#000000' },
  { src: 'gallery/lightbox/lukasz-jagiello-05-full.webp', thumb: 'gallery/lukasz-jagiello-05-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 5', title: 'Photograph 5', width: 1600, height: 2399, color: '#515e61' },
  { src: 'gallery/lightbox/lukasz-jagiello-06-full.webp', thumb: 'gallery/lukasz-jagiello-06-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 6', title: 'Photograph 6', width: 1600, height: 1067, color: '#e1d8c7' },
  { src: 'gallery/lightbox/lukasz-jagiello-07-full.webp', thumb: 'gallery/lukasz-jagiello-07-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 7', title: 'Photograph 7', width: 1600, height: 1067, color: '#031720' },
  { src: 'gallery/lightbox/lukasz-jagiello-08-full.webp', thumb: 'gallery/lukasz-jagiello-08-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 8', title: 'Photograph 8', width: 1600, height: 2399, color: '#b8d1f0' },
  { src: 'gallery/lightbox/lukasz-jagiello-09-full.webp', thumb: 'gallery/lukasz-jagiello-09-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 9', title: 'Photograph 9', width: 1600, height: 2399, color: '#02170b' },
  { src: 'gallery/lightbox/lukasz-jagiello-10-full.webp', thumb: 'gallery/lukasz-jagiello-10-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 10', title: 'Photograph 10', width: 1600, height: 2399, color: '#031b0e' },
  { src: 'gallery/lightbox/lukasz-jagiello-11-full.webp', thumb: 'gallery/lukasz-jagiello-11-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 11', title: 'Photograph 11', width: 1600, height: 900, color: '#9fc7c6' },
  { src: 'gallery/lightbox/lukasz-jagiello-12-full.webp', thumb: 'gallery/lukasz-jagiello-12-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 12', title: 'Photograph 12', width: 1600, height: 2400, color: '#00a6cd' },
  { src: 'gallery/lightbox/lukasz-jagiello-13-full.webp', thumb: 'gallery/lukasz-jagiello-13-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 13', title: 'Photograph 13', width: 1600, height: 2399, color: '#202020' },
  { src: 'gallery/lightbox/lukasz-jagiello-14-full.webp', thumb: 'gallery/lukasz-jagiello-14-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 14', title: 'Photograph 14', width: 1600, height: 900, color: '#012273' },
  { src: 'gallery/lightbox/lukasz-jagiello-15-full.webp', thumb: 'gallery/lukasz-jagiello-15-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 15', title: 'Photograph 15', width: 1600, height: 1067, color: '#004586' },
  { src: 'gallery/lightbox/lukasz-jagiello-16-full.webp', thumb: 'gallery/lukasz-jagiello-16-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 16', title: 'Photograph 16', width: 1600, height: 2400, color: '#0056a9' },
  { src: 'gallery/lightbox/lukasz-jagiello-17-full.webp', thumb: 'gallery/lukasz-jagiello-17-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 17', title: 'Photograph 17', width: 1600, height: 2070, color: '#000000' },
  { src: 'gallery/lightbox/lukasz-jagiello-18-full.webp', thumb: 'gallery/lukasz-jagiello-18-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 18', title: 'Photograph 18', width: 1600, height: 1000, color: '#01001f' },
  { src: 'gallery/lightbox/lukasz-jagiello-19-full.webp', thumb: 'gallery/lukasz-jagiello-19-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 19', title: 'Photograph 19', width: 1600, height: 2399, color: '#737d96' },
  { src: 'gallery/lightbox/lukasz-jagiello-20-full.webp', thumb: 'gallery/lukasz-jagiello-20-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 20', title: 'Photograph 20', width: 1600, height: 2399, color: '#001c00' },
  { src: 'gallery/lightbox/lukasz-jagiello-21-full.webp', thumb: 'gallery/lukasz-jagiello-21-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 21', title: 'Photograph 21', width: 1600, height: 2399, color: '#004400' },
  { src: 'gallery/lightbox/lukasz-jagiello-22-full.webp', thumb: 'gallery/lukasz-jagiello-22-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 22', title: 'Photograph 22', width: 1600, height: 1143, color: '#000a00' },
  { src: 'gallery/lightbox/lukasz-jagiello-23-full.webp', thumb: 'gallery/lukasz-jagiello-23-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 23', title: 'Photograph 23', width: 1600, height: 2399, color: '#011401' },
  { src: 'gallery/lightbox/lukasz-jagiello-24-full.webp', thumb: 'gallery/lukasz-jagiello-24-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 24', title: 'Photograph 24', width: 1600, height: 1067, color: '#cca478' },
  { src: 'gallery/lightbox/lukasz-jagiello-25-full.webp', thumb: 'gallery/lukasz-jagiello-25-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 25', title: 'Photograph 25', width: 1600, height: 1067, color: '#000000' },
  { src: 'gallery/lightbox/lukasz-jagiello-26-full.webp', thumb: 'gallery/lukasz-jagiello-26-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 26', title: 'Photograph 26', width: 1600, height: 1060, color: '#000000' },
  { src: 'gallery/lightbox/lukasz-jagiello-27-full.webp', thumb: 'gallery/lukasz-jagiello-27-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 27', title: 'Photograph 27', width: 1600, height: 1067, color: '#91c5fb' },
  { src: 'gallery/lightbox/lukasz-jagiello-28-full.webp', thumb: 'gallery/lukasz-jagiello-28-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 28', title: 'Photograph 28', width: 1600, height: 2399, color: '#000000' },
  { src: 'gallery/lightbox/lukasz-jagiello-29-full.webp', thumb: 'gallery/lukasz-jagiello-29-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 29', title: 'Photograph 29', width: 1600, height: 1067, color: '#060c07' },
  { src: 'gallery/lightbox/lukasz-jagiello-30-full.webp', thumb: 'gallery/lukasz-jagiello-30-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 30', title: 'Photograph 30', width: 1600, height: 1230, color: '#f2e9e2' },
  { src: 'gallery/lightbox/lukasz-jagiello-31-full.webp', thumb: 'gallery/lukasz-jagiello-31-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 31', title: 'Photograph 31', width: 1600, height: 2845, color: '#39474f' },
  { src: 'gallery/lightbox/lukasz-jagiello-32-full.webp', thumb: 'gallery/lukasz-jagiello-32-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 32', title: 'Photograph 32', width: 1600, height: 900, color: '#007cb2' },
  { src: 'gallery/lightbox/lukasz-jagiello-33-full.webp', thumb: 'gallery/lukasz-jagiello-33-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 33', title: 'Photograph 33', width: 1600, height: 2845, color: '#fcfcfc' },
  { src: 'gallery/lightbox/lukasz-jagiello-34-full.webp', thumb: 'gallery/lukasz-jagiello-34-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 34', title: 'Photograph 34', width: 1600, height: 2272, color: '#fafafa' },
  { src: 'gallery/lightbox/lukasz-jagiello-35-full.webp', thumb: 'gallery/lukasz-jagiello-35-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 35', title: 'Photograph 35', width: 1600, height: 2036, color: '#56371c' },
  { src: 'gallery/lightbox/lukasz-jagiello-36-full.webp', thumb: 'gallery/lukasz-jagiello-36-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 36', title: 'Photograph 36', width: 1600, height: 2399, color: '#1a1610' },
  { src: 'gallery/lightbox/lukasz-jagiello-37-full.webp', thumb: 'gallery/lukasz-jagiello-37-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 37', title: 'Photograph 37', width: 1600, height: 2473, color: '#f3f4f8' },
  { src: 'gallery/lightbox/lukasz-jagiello-38-full.webp', thumb: 'gallery/lukasz-jagiello-38-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 38', title: 'Photograph 38', width: 1600, height: 1067, color: '#100e0e' },
  { src: 'gallery/lightbox/lukasz-jagiello-39-full.webp', thumb: 'gallery/lukasz-jagiello-39-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 39', title: 'Photograph 39', width: 1600, height: 1000, color: '#221a18' },
  { src: 'gallery/lightbox/lukasz-jagiello-40-full.webp', thumb: 'gallery/lukasz-jagiello-40-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 40', title: 'Photograph 40', width: 1600, height: 2071, color: '#080401' },
  { src: 'gallery/lightbox/lukasz-jagiello-41-full.webp', thumb: 'gallery/lukasz-jagiello-41-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 41', title: 'Photograph 41', width: 1600, height: 1000, color: '#020709' },
  { src: 'gallery/lightbox/lukasz-jagiello-42-full.webp', thumb: 'gallery/lukasz-jagiello-42-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 42', title: 'Photograph 42', width: 1600, height: 1067, color: '#010101' },
  { src: 'gallery/lightbox/lukasz-jagiello-43-full.webp', thumb: 'gallery/lukasz-jagiello-43-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 43', title: 'Photograph 43', width: 1600, height: 1067, color: '#3d342e' },
  { src: 'gallery/lightbox/lukasz-jagiello-44-full.webp', thumb: 'gallery/lukasz-jagiello-44-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 44', title: 'Photograph 44', width: 1600, height: 2400, color: '#010101' },
  { src: 'gallery/lightbox/lukasz-jagiello-45-full.webp', thumb: 'gallery/lukasz-jagiello-45-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 45', title: 'Photograph 45', width: 1600, height: 2400, color: '#010101' },
  { src: 'gallery/lightbox/lukasz-jagiello-46-full.webp', thumb: 'gallery/lukasz-jagiello-46-thumb.webp', alt: 'Łukasz Jagiełło landscape photograph number 46', title: 'Photograph 46', width: 1600, height: 2400, color: '#000000' },
];

export const hero = {
  src: '/images/lukasz-jagiello-hero.webp',
  alt: 'Pacific coastline at golden hour with layered headlands fading into haze',
};
